name: Build and publish testing image
on: [workflow_dispatch]
jobs:
  build-and-publish-testing-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: >
          cp pyproject.toml docker_testing_environment

          docker image build
          -t ghcr.io/lukasturcani/smores-testing-environment:latest
          ./docker_testing_environment

      - name: Publish image
        run: docker push ghcr.io/lukasturcani/smores-testing-environment:latest
