name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/smores-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Lint with flake8
        run: . /code/venv/bin/activate && flake8 .
