name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/smores-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Lint with flake8
        run: |
          . /deps/venv/bin/activate
          flake8 .
  mypy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/lukasturcani/smores-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run mypy
        run: |
          . /deps/venv/bin/activate
          pip install --no-deps -e .
          mypy --exclude validation .
          mypy --explicit-package-bases validation
